FROM registry.access.redhat.com/ubi9:9.6

ARG USER_HOME_DIR="/home/user"
ARG INSTALL_PACKAGES="openssl shadow-utils xz bash"
ARG NODE_VERSION="v18.20.8"

ENV HOME=${USER_HOME_DIR}
ENV PATH=${PATH}:/usr/local/node/bin

COPY --chown=0:0 entrypoint.sh /
COPY --chown=0:0 server.js /usr/local/www/

RUN set -e ; \
  dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm ; \
  dnf install -y ${INSTALL_PACKAGES} ; \
  dnf update -y ; \
  dnf clean all ; \
  mkdir -p /usr/local/bin ; \
  chmod +x /entrypoint.sh ; \
  #
  # Install NodeJS
  #
  TEMP_DIR="$(mktemp -d)" ; \
  curl -fsSL -o ${TEMP_DIR}/node.tz https://nodejs.org/dist/${NODE_VERSION}/node-${NODE_VERSION}-linux-x64.tar.xz ; \
  tar -x --no-auto-compress -f ${TEMP_DIR}/node.tz -C ${TEMP_DIR} ; \
  mv ${TEMP_DIR}/node-${NODE_VERSION}-linux-x64 /usr/local/node ; \
  rm -rf "${TEMP_DIR}" ; \
  mkdir -p ${USER_HOME_DIR} ; \
  chmod -R g=u /etc/passwd /etc/group /home

USER 1000
WORKDIR ${WORK_DIR}
ENTRYPOINT ["/entrypoint.sh"]
CMD [ "tail", "-f", "/dev/null" ]
